  /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.MeyrClientesDAO;
import bean.MeyrClientes;
import bean.MeyrVendas;
import bean.MeyrVendasRemedios;
import bean.MeyrVendedor;
import dao.MeyrVendasDAO;
import dao.MeyrVendasRemediosDAO;
import dao.MeyrVendedorDAO;
import java.text.ParseException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import tools.Util;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;


/**
 *
 * @author u1845853
 */
public class MeyrjDlgVendas extends javax.swing.JDialog {
    
    MeyrControllerVendasRemedios  meyrControllerVendasRemedios;

    /**
     * Creates new form JDlgPedidos
     */
    private boolean incluir;
    boolean pesquisando = false;
    private MaskFormatter mascaraDataCadastro;
    public MeyrjDlgVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Vendas");
        setLocationRelativeTo(null);
        
        Util.habilitar(false, meyrjTxtIdVenda, meyrFmtDataVenda, meyrCboIdCliente, meyrCboIdVendedor, meyrjTxtTotalVenda,
                jBtnConfirmar, jBtnCancelar, jBtnIncluirProd, jBtnAlterarProd, jBtnExcluirProd);
        Util.habilitar(true, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
        
        try {
             mascaraDataCadastro = new MaskFormatter("##/##/####");
             meyrFmtDataVenda.setFormatterFactory(new DefaultFormatterFactory(mascaraDataCadastro));
            } catch (ParseException ex) {
            Logger.getLogger(MeyrjDlgClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        

           MeyrClientesDAO clientesDAO = new MeyrClientesDAO();
            List<MeyrClientes> listaClientes = clientesDAO.listAll();
            for (MeyrClientes cliente : listaClientes) {
                meyrCboIdCliente.addItem(cliente);
            }

            MeyrVendedorDAO meyrVendedorDAO = new MeyrVendedorDAO();
            List<MeyrVendedor> listaVendedores = meyrVendedorDAO.listAll();
            for (MeyrVendedor vendedor : listaVendedores) {
                meyrCboIdVendedor.addItem(vendedor);
}
            
            meyrControllerVendasRemedios = new MeyrControllerVendasRemedios();
            meyrControllerVendasRemedios.setList(new ArrayList());
            jTable1.setModel(meyrControllerVendasRemedios);
    }

    public MeyrVendas viewBean() {
    MeyrVendas meyrVendas = new MeyrVendas();
    String idText = meyrjTxtIdVenda.getText();
    if (idText != null && !idText.isEmpty()) {
        meyrVendas.setMeyrIdVenda(Util.strToInt(idText));
    } else {
        meyrVendas.setMeyrIdVenda(0);
    }
    meyrVendas.setMeyrClientes((MeyrClientes) meyrCboIdCliente.getSelectedItem());
    meyrVendas.setMeyrVendedor((MeyrVendedor) meyrCboIdVendedor.getSelectedItem());
    meyrVendas.setMeyrTotalVenda(Util.strToBigDecimal(meyrjTxtTotalVenda.getText()));
    meyrVendas.setMeyrDataVenda(Util.strToDate(meyrFmtDataVenda.getText()));
    return meyrVendas;
}

    /**
     *
     * @return
     */
     public void beanView(MeyrVendas meyrVendas) {
        meyrjTxtIdVenda.setText(Util.intToStr(meyrVendas.getMeyrIdVenda()));
        meyrCboIdCliente.setSelectedItem(meyrVendas.getMeyrClientes());
        meyrCboIdVendedor.setSelectedItem(meyrVendas.getMeyrVendedor());
        meyrFmtDataVenda.setText(Util.dateToStr(meyrVendas.getMeyrDataVenda()));
        meyrFmtDataVenda.setText(Util.dateToStr(meyrVendas.getMeyrDataVenda()));
        MeyrVendasRemediosDAO meyrVendasRemediosDAO = new MeyrVendasRemediosDAO();
        List lista = (List) meyrVendasRemediosDAO.listProutos(meyrVendas);
        meyrControllerVendasRemedios.setList(lista);
    }
     public JTable getjTable1() {
        return jTable1;
    }
     public void somarTotais() {
        double total = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            Object valorObj = jTable1.getModel().getValueAt(i, 3);
            if (valorObj != null) {
                try {
                    double valor = Double.parseDouble(valorObj.toString().replace(",", "."));
                    total += valor;
                } catch (Exception e) {
                }
            }
        }
        meyrjTxtTotalVenda.setText(String.valueOf(total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        meyrjLbllUltimaModificacao2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        meyrjTxtIdVenda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        meyrFmtDataVenda = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        meyrCboIdCliente = new javax.swing.JComboBox<MeyrClientes>();
        meyrCboIdVendedor = new javax.swing.JComboBox<MeyrVendedor>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        meyrjTxtTotalVenda = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        meyrjLbllUltimaModificacao = new javax.swing.JLabel();
        jBtnIncluirProd = new javax.swing.JButton();
        jBtnAlterarProd = new javax.swing.JButton();
        jBtnExcluirProd = new javax.swing.JButton();

        meyrjLbllUltimaModificacao2.setText("Ultima Modificação as:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Codigo");

        meyrjTxtIdVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meyrjTxtIdVendaActionPerformed(evt);
            }
        });

        jLabel2.setText("Data");

        meyrFmtDataVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meyrFmtDataVendaActionPerformed(evt);
            }
        });

        jLabel3.setText("Clientes");

        jLabel4.setText("Vendedor");

        jLabel5.setText("Total");

        meyrjTxtTotalVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meyrjTxtTotalVendaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        meyrjLbllUltimaModificacao.setText("Ultima Modificação as:");

        jBtnIncluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluirProd.setToolTipText("");
        jBtnIncluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirProdActionPerformed(evt);
            }
        });

        jBtnAlterarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarProdActionPerformed(evt);
            }
        });

        jBtnExcluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnAlterarProd)
                                    .addComponent(jBtnIncluirProd)
                                    .addComponent(jBtnExcluirProd)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(meyrjTxtIdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(meyrFmtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(meyrCboIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(meyrCboIdVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(meyrjTxtTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jBtnIncluir)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtnAlterar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtnExcluir)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtnConfirmar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtnCancelar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtnPesquisar)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(meyrjLbllUltimaModificacao)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(meyrjTxtIdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(meyrFmtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(meyrCboIdVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(meyrjTxtTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(meyrCboIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jBtnIncluirProd)
                        .addGap(29, 29, 29)
                        .addComponent(jBtnAlterarProd)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnExcluirProd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(meyrjLbllUltimaModificacao)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true,jBtnIncluirProd,jBtnAlterarProd,jBtnExcluirProd,meyrjTxtIdVenda, meyrFmtDataVenda, meyrCboIdCliente, meyrCboIdVendedor, meyrjTxtTotalVenda, jBtnConfirmar, jBtnCancelar, jTable1);

        Util.habilitar(false, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);

        Util.limpar(meyrjTxtIdVenda, meyrFmtDataVenda, meyrCboIdCliente, meyrCboIdVendedor, meyrjTxtTotalVenda);
        meyrjTxtIdVenda.grabFocus();
        incluir = true;
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, meyrFmtDataVenda, meyrCboIdCliente, meyrCboIdVendedor, meyrjTxtTotalVenda, jBtnConfirmar, jBtnCancelar, jBtnAlterarProd,jBtnIncluirProd,jBtnExcluirProd);
        Util.habilitar(false, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
        meyrjTxtIdVenda.grabFocus();

        incluir = false;
      
       LocalDateTime agora = LocalDateTime.now();
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
            meyrjLbllUltimaModificacao.setText("Última modificação: " + agora.format(formato));
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
          // TODO add your handling code here:
          if (Util.perguntar("Deseja excluir ?") == true) {
            MeyrVendasDAO meyrVendasDAO = new MeyrVendasDAO();       
              MeyrVendasRemediosDAO meyrVendasRemediosDAO = new MeyrVendasRemediosDAO();
            
               
              for (int ind = 0; ind < jTable1.getRowCount(); ind++) {
                  MeyrVendasRemedios meyrVendasRemedios = meyrControllerVendasRemedios.getBean(ind);
                meyrVendasRemediosDAO.delete(meyrVendasRemedios);
            }
               meyrVendasDAO.delete(viewBean()); 
        }
        Util.limpar(meyrjTxtIdVenda, meyrFmtDataVenda, meyrCboIdCliente, meyrCboIdVendedor, meyrjTxtTotalVenda, jBtnConfirmar, jBtnCancelar);
        meyrControllerVendasRemedios.setList(new ArrayList());
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
         // TODO add your handling code here:
        LocalDateTime agora = LocalDateTime.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        meyrjLbllUltimaModificacao.setText("Última modificação: " + agora.format(formato));

        MeyrVendasDAO meyrVendasDAO = new MeyrVendasDAO();
        MeyrVendasRemediosDAO meyrVendasRemediosDAO = new MeyrVendasRemediosDAO();
        MeyrVendas meyrVendas = viewBean();

        if (incluir == true) {

            meyrVendasDAO.insert(meyrVendas);

            for (int ind = 0; ind < jTable1.getRowCount(); ind++) {
                MeyrVendasRemedios meyrVendasRemedios = meyrControllerVendasRemedios.getBean(ind);
                meyrVendasRemedios.setMeyrVendas(meyrVendas);
                meyrVendasRemediosDAO.insert(meyrVendasRemedios);
            }

        } else {

            meyrVendasDAO.update(meyrVendas);
            meyrVendasRemediosDAO.deleteByVenda(meyrVendas);
            for (int ind = 0; ind < jTable1.getRowCount(); ind++) {
                MeyrVendasRemedios meyrVendasRemedios = meyrControllerVendasRemedios.getBean(ind);
                meyrVendasRemedios.setMeyrVendas(meyrVendas);
                meyrVendasRemediosDAO.insert(meyrVendasRemedios);
            }
        }
        Util.habilitar(false, meyrjTxtIdVenda, meyrFmtDataVenda, meyrCboIdCliente, meyrCboIdVendedor, meyrjTxtTotalVenda,
                jBtnConfirmar, jBtnCancelar);
        Util.habilitar(true, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
        Util.limpar(meyrjTxtIdVenda, meyrFmtDataVenda, meyrCboIdCliente, meyrCboIdVendedor, meyrjTxtTotalVenda);
        meyrControllerVendasRemedios.setList(new ArrayList());
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false,meyrCboIdCliente, meyrFmtDataVenda, meyrCboIdCliente, meyrCboIdVendedor, meyrjTxtTotalVenda);
        Util.habilitar(true, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
        Util.limpar(meyrCboIdCliente, meyrFmtDataVenda, meyrCboIdCliente, meyrCboIdVendedor, meyrjTxtTotalVenda);
        
        LocalDateTime agora = LocalDateTime.now();
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
            meyrjLbllUltimaModificacao.setText("Última modificação: " + agora.format(formato));
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        MeyrJDlgVendasPesquisar meyrJDlgVendasPesquisar = new MeyrJDlgVendasPesquisar(null, true);
        meyrJDlgVendasPesquisar.setTelaPai(this);
        meyrJDlgVendasPesquisar.setVisible(true);
        
        
        LocalDateTime agora = LocalDateTime.now();
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
            meyrjLbllUltimaModificacao.setText("Última modificação: " + agora.format(formato));
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void meyrFmtDataVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meyrFmtDataVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meyrFmtDataVendaActionPerformed

    private void meyrjTxtTotalVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meyrjTxtTotalVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meyrjTxtTotalVendaActionPerformed

    private void jBtnIncluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirProdActionPerformed
        // TODO add your handling code here:
        MeyrVendasRememedios  meyrVendasRememedios = new MeyrVendasRememedios(null, true);
        meyrVendasRememedios.setTelaAnterior(this);
        meyrVendasRememedios.setIncluir(true);
        meyrVendasRememedios.setVisible(true);
        somarTotais();

    }//GEN-LAST:event_jBtnIncluirProdActionPerformed

    private void jBtnAlterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarProdActionPerformed
        // TODO add your handling code here:
            MeyrVendasRememedios meyrVendasRememedios = new MeyrVendasRememedios(null, true);
            meyrVendasRememedios.setTelaAnterior(this);
            meyrVendasRememedios.setVisible(true);

    }//GEN-LAST:event_jBtnAlterarProdActionPerformed

    private void jBtnExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirProdActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() != -1) { // Verifica se há uma linha selecionada
            if (Util.perguntar("Deseja Excluir?")) {
                int rowindex = jTable1.getSelectedRow();
                meyrControllerVendasRemedios.removeBean(rowindex);
                somarTotais();
            }
        } else {
            Util.mensagem("Selecione uma linha para excluir!");
        }
    }//GEN-LAST:event_jBtnExcluirProdActionPerformed

    private void meyrjTxtIdVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meyrjTxtIdVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meyrjTxtIdVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeyrjDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeyrjDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeyrjDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeyrjDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MeyrjDlgVendas dialog = new MeyrjDlgVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnAlterarProd;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnExcluirProd;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnIncluirProd;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<MeyrClientes> meyrCboIdCliente;
    private javax.swing.JComboBox<MeyrVendedor> meyrCboIdVendedor;
    private javax.swing.JFormattedTextField meyrFmtDataVenda;
    private javax.swing.JLabel meyrjLbllUltimaModificacao;
    private javax.swing.JLabel meyrjLbllUltimaModificacao2;
    private javax.swing.JTextField meyrjTxtIdVenda;
    private javax.swing.JTextField meyrjTxtTotalVenda;
    // End of variables declaration//GEN-END:variables

    
}
