package view;

import bean.MeyrClientes;
import bean.MeyrVendas;
import bean.MeyrVendedor;
import tools.Util;
import view.MeyrJDlgVendasPesquisar;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author Mathias Eduardo
 */
public class MeyrjDlgVendas extends javax.swing.JDialog {

    /**
     * Creates new form MeyrjDlgVendas
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
         boolean pesquisando = false;
        public MeyrjDlgVendas(java.awt.Frame parent, boolean modal) {
            super(parent, modal);
            initComponents();
            setTitle("Cadastro de Vendas");
            setLocationRelativeTo(null);
                Util.habilitar(false, 
                    meyrjTxtCodigoVenda, 
                    meyrjFmtDataVenda, 
                    meyrjCboVendedor, 
                    meyrjCboFormaPagamento, 
                    meyrjTxtObservacoes, 
                    meyrjTxtTotalVenda, 
                    meyrjTxtStatus, 
                    meyrjBtnConfirmar,
                    meyrjCboCliente,
                    meyrjBtnCancelar
    );
}       
        public MeyrVendas viewBean() {
    MeyrVendas meyrVendas = new MeyrVendas();

    meyrVendas.setMeyrClientes((MeyrClientes) meyrjCboCliente.getSelectedItem());
    meyrVendas.setMeyrVendedor((MeyrVendedor) meyrjCboVendedor.getSelectedItem());
    meyrVendas.setMeyrDataVenda(Util.strToDate(meyrjFmtDataVenda.getText()));
    meyrVendas.setMeyrTotalVenda(Util.strToDuble(meyrjTxtTotalVenda.getText()));
    meyrVendas.setMeyrFormaPagamento(meyrjCboFormaPagamento.getSelectedItem().toString());
    meyrVendas.setMeyrStatus(meyrjTxtStatus.getText());
    meyrVendas.setMeyrObservacoes(meyrjTxtObservacoes.getText());

    return meyrVendas;
}

public void beanView(MeyrVendas meyrVendas) {
    meyrjCboCliente.setSelectedItem(meyrVendas.getMeyrClientes());
    meyrjCboVendedor.setSelectedItem(meyrVendas.getMeyrVendedor());
    meyrjFmtDataVenda.setText(Util.dateToStr(meyrVendas.getMeyrDataVenda()));
    meyrjTxtTotalVenda.setText(Util.doubleToStr(meyrVendas.getMeyrTotalVenda()));
    meyrjCboFormaPagamento.setSelectedItem(meyrVendas.getMeyrFormaPagamento());
    meyrjTxtStatus.setText(meyrVendas.getMeyrStatus());
    meyrjTxtObservacoes.setText(meyrVendas.getMeyrObservacoes());
}

    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        meyrjLblCadastroVendas = new javax.swing.JLabel();
        meyrjLblCodigoVenda = new javax.swing.JLabel();
        meyrjTxtCodigoVenda = new javax.swing.JTextField();
        meyrjLblDateVenda = new javax.swing.JLabel();
        meyrjLblCodigoCliente = new javax.swing.JLabel();
        meyrjLblTotalVenda = new javax.swing.JLabel();
        meyrjTxtTotalVenda = new javax.swing.JTextField();
        meyrjLblFormaPagamento = new javax.swing.JLabel();
        meyrjLblStatus = new javax.swing.JLabel();
        meyrjTxtStatus = new javax.swing.JTextField();
        meyrjLblRemedio = new javax.swing.JLabel();
        meyrjTxtObservacoes = new javax.swing.JTextField();
        MeyrjBntPesquisar = new javax.swing.JButton();
        meyrjButtonIncluir = new javax.swing.JButton();
        meyrjBtnConfirmar = new javax.swing.JButton();
        meyrjBtnAlterar = new javax.swing.JButton();
        meyrjBtnCancelar = new javax.swing.JButton();
        meyrjBtnExcluir = new javax.swing.JButton();
        meyrjCboCliente = new javax.swing.JComboBox<>();
        meyrjCboVendedor = new javax.swing.JComboBox<>();
        meyrjCboFormaPagamento = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        meyrjFmtDataVenda = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        meyrjLblCadastroVendas.setText("Cadastro de Vendas");

        meyrjLblCodigoVenda.setText("Código da Venda");

        meyrjTxtCodigoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meyrjTxtCodigoVendaActionPerformed(evt);
            }
        });

        meyrjLblDateVenda.setText("Data da Venda:");

        meyrjLblCodigoCliente.setText("Código do Cliente:");

        meyrjLblTotalVenda.setText("Total da Venda:");

        meyrjTxtTotalVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meyrjTxtTotalVendaActionPerformed(evt);
            }
        });

        meyrjLblFormaPagamento.setText("Forma de Pagamento:");

        meyrjLblStatus.setText("Status:");

        meyrjTxtStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meyrjTxtStatusActionPerformed(evt);
            }
        });

        meyrjLblRemedio.setText("Código do Vendedor:");

        meyrjTxtObservacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meyrjTxtObservacoesActionPerformed(evt);
            }
        });

        MeyrjBntPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        MeyrjBntPesquisar.setText("Pesquisar");
        MeyrjBntPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeyrjBntPesquisarActionPerformed(evt);
            }
        });

        meyrjButtonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        meyrjButtonIncluir.setText("Incluir");
        meyrjButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meyrjButtonIncluirActionPerformed(evt);
            }
        });

        meyrjBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        meyrjBtnConfirmar.setText("Confirmar");
        meyrjBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meyrjBtnConfirmarActionPerformed(evt);
            }
        });

        meyrjBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        meyrjBtnAlterar.setText("Alterar");
        meyrjBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meyrjBtnAlterarActionPerformed(evt);
            }
        });

        meyrjBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        meyrjBtnCancelar.setText("Cancelar");
        meyrjBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meyrjBtnCancelarActionPerformed(evt);
            }
        });

        meyrjBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        meyrjBtnExcluir.setText("Excluir");
        meyrjBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meyrjBtnExcluirActionPerformed(evt);
            }
        });

        meyrjCboVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meyrjCboVendedorActionPerformed(evt);
            }
        });

        meyrjCboFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Pix", "Debito", "Credito" }));

        jLabel1.setText("Obsevacoes:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(meyrjTxtObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(meyrjLblDateVenda)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(meyrjFmtDataVenda)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(meyrjLblTotalVenda)
                                    .addComponent(meyrjTxtTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(meyrjLblRemedio)
                                    .addComponent(meyrjCboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(meyrjLblStatus)
                                    .addComponent(meyrjTxtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(meyrjLblFormaPagamento)
                                    .addComponent(meyrjCboFormaPagamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(meyrjTxtCodigoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(meyrjLblCodigoVenda))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(meyrjLblCodigoCliente)
                                    .addComponent(meyrjCboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(meyrjBtnConfirmar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(meyrjButtonIncluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(meyrjBtnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(meyrjBtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(meyrjBtnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(MeyrjBntPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(meyrjLblCadastroVendas)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(meyrjLblCadastroVendas)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(meyrjLblCodigoVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(meyrjTxtCodigoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(meyrjCboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(meyrjLblCodigoCliente)
                        .addGap(32, 32, 32)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meyrjLblDateVenda)
                    .addComponent(meyrjLblRemedio)
                    .addComponent(meyrjLblFormaPagamento))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meyrjCboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meyrjCboFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meyrjFmtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meyrjLblTotalVenda)
                    .addComponent(meyrjLblStatus)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meyrjTxtObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meyrjTxtTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meyrjTxtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meyrjButtonIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meyrjBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meyrjBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meyrjBtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meyrjBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MeyrjBntPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meyrjTxtCodigoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meyrjTxtCodigoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meyrjTxtCodigoVendaActionPerformed

    private void meyrjTxtTotalVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meyrjTxtTotalVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meyrjTxtTotalVendaActionPerformed

    private void meyrjTxtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meyrjTxtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meyrjTxtStatusActionPerformed

    private void meyrjTxtObservacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meyrjTxtObservacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meyrjTxtObservacoesActionPerformed

    private void MeyrjBntPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeyrjBntPesquisarActionPerformed
        MeyrJDlgVendasPesquisar meyrJDlgVendasPesquisar = new MeyrJDlgVendasPesquisar(null, true);
        meyrJDlgVendasPesquisar.setTelaPai(this);
        meyrJDlgVendasPesquisar.setVisible(true);
        pesquisando = true;
    }//GEN-LAST:event_MeyrjBntPesquisarActionPerformed

    private void meyrjButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meyrjButtonIncluirActionPerformed
        Util.habilitar(true, meyrjTxtCodigoVenda, meyrjCboCliente, meyrjFmtDataVenda, meyrjCboVendedor, meyrjCboFormaPagamento, meyrjTxtObservacoes, meyrjTxtTotalVenda, meyrjTxtStatus, meyrjBtnConfirmar, meyrjBtnCancelar);  
        Util.habilitar(false, meyrjButtonIncluir, meyrjBtnAlterar, meyrjBtnExcluir, MeyrjBntPesquisar);  
        Util.limpar(meyrjTxtCodigoVenda, meyrjCboCliente, meyrjFmtDataVenda, meyrjCboVendedor, meyrjCboFormaPagamento, meyrjTxtObservacoes, meyrjTxtTotalVenda, meyrjTxtStatus);

    }//GEN-LAST:event_meyrjButtonIncluirActionPerformed

    private void meyrjBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meyrjBtnConfirmarActionPerformed
        Util.habilitar(false, meyrjTxtCodigoVenda, meyrjCboCliente, meyrjFmtDataVenda, meyrjCboVendedor, meyrjCboFormaPagamento, meyrjTxtObservacoes, meyrjTxtTotalVenda, meyrjTxtStatus, meyrjBtnConfirmar, meyrjBtnCancelar);  
        Util.habilitar(true, meyrjButtonIncluir, meyrjBtnAlterar, meyrjBtnExcluir, MeyrjBntPesquisar);

    }//GEN-LAST:event_meyrjBtnConfirmarActionPerformed

    private void meyrjBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meyrjBtnAlterarActionPerformed
        Util.habilitar(true, meyrjCboCliente, meyrjFmtDataVenda, meyrjCboVendedor, meyrjCboFormaPagamento, meyrjTxtObservacoes, meyrjTxtTotalVenda, meyrjTxtStatus, meyrjBtnConfirmar, meyrjBtnCancelar);  
        Util.habilitar(false, meyrjButtonIncluir, meyrjBtnAlterar, meyrjBtnExcluir, MeyrjBntPesquisar);

    }//GEN-LAST:event_meyrjBtnAlterarActionPerformed

    private void meyrjBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meyrjBtnCancelarActionPerformed
        Util.habilitar(false, meyrjTxtCodigoVenda, meyrjCboCliente, meyrjFmtDataVenda, meyrjCboVendedor, meyrjCboFormaPagamento, meyrjTxtObservacoes, meyrjTxtTotalVenda, meyrjTxtStatus, meyrjBtnConfirmar, meyrjBtnCancelar);  
        Util.habilitar(true, meyrjButtonIncluir, meyrjBtnAlterar, meyrjBtnExcluir, MeyrjBntPesquisar);

    }//GEN-LAST:event_meyrjBtnCancelarActionPerformed

    private void meyrjBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meyrjBtnExcluirActionPerformed
     if (pesquisando == false) {
            Util.mensagem("Você precisa pesquisar um usuário primeiro");
        } else {
                Util.perguntar("Você deseja excluir?");
                Util.limpar( meyrjTxtCodigoVenda, 
                    meyrjFmtDataVenda, 
                    meyrjCboVendedor, 
                    meyrjCboFormaPagamento, 
                    meyrjTxtObservacoes, 
                    meyrjTxtTotalVenda, 
                    meyrjTxtStatus, 
                    meyrjCboCliente);
     } 
    }//GEN-LAST:event_meyrjBtnExcluirActionPerformed

    private void meyrjCboVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meyrjCboVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meyrjCboVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            MeyrjDlgVendas dialog = new MeyrjDlgVendas(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        }
    });
} 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MeyrjBntPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton meyrjBtnAlterar;
    private javax.swing.JButton meyrjBtnCancelar;
    private javax.swing.JButton meyrjBtnConfirmar;
    private javax.swing.JButton meyrjBtnExcluir;
    private javax.swing.JButton meyrjButtonIncluir;
    private javax.swing.JComboBox<String> meyrjCboCliente;
    private javax.swing.JComboBox<String> meyrjCboFormaPagamento;
    private javax.swing.JComboBox<String> meyrjCboVendedor;
    private javax.swing.JFormattedTextField meyrjFmtDataVenda;
    private javax.swing.JLabel meyrjLblCadastroVendas;
    private javax.swing.JLabel meyrjLblCodigoCliente;
    private javax.swing.JLabel meyrjLblCodigoVenda;
    private javax.swing.JLabel meyrjLblDateVenda;
    private javax.swing.JLabel meyrjLblFormaPagamento;
    private javax.swing.JLabel meyrjLblRemedio;
    private javax.swing.JLabel meyrjLblStatus;
    private javax.swing.JLabel meyrjLblTotalVenda;
    private javax.swing.JTextField meyrjTxtCodigoVenda;
    private javax.swing.JTextField meyrjTxtObservacoes;
    private javax.swing.JTextField meyrjTxtStatus;
    private javax.swing.JTextField meyrjTxtTotalVenda;
    // End of variables declaration//GEN-END:variables
}
