package view;


import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mathias Eduardo
 */
public class MeyrJFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form jFrameprincipal
     */
    public MeyrJFrmPrincipal() {
        initComponents();
        getContentPane().setBackground(new Color(240,255,255));
        setTitle("SIstema Vendas Farmacia");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        meyrjMenuItem1 = new javax.swing.JMenuItem();
        jSplitPane1 = new javax.swing.JSplitPane();
        jSeparator2 = new javax.swing.JSeparator();
        meyrjMenuBar1 = new javax.swing.JMenuBar();
        meyrjMnuUsuarios = new javax.swing.JMenu();
        meyrjMnuCliente = new javax.swing.JMenuItem();
        meyrjMnuUsuarioss = new javax.swing.JMenuItem();
        meyrjMnuVendedor = new javax.swing.JMenuItem();
        meyrjMnuProdutos = new javax.swing.JMenuItem();
        meyrjMnuSair = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        meyrjMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        meyrjMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        meyrjMnuUsuarios.setText("Cadastro");
        meyrjMnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meyrjMnuUsuariosActionPerformed(evt);
            }
        });

        meyrjMnuCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        meyrjMnuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        meyrjMnuCliente.setText("Cliente");
        meyrjMnuCliente.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                meyrjMnuClienteComponentAdded(evt);
            }
        });
        meyrjMnuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meyrjMnuClienteActionPerformed(evt);
            }
        });
        meyrjMnuUsuarios.add(meyrjMnuCliente);

        meyrjMnuUsuarioss.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        meyrjMnuUsuarioss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        meyrjMnuUsuarioss.setText("Usuario");
        meyrjMnuUsuarioss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meyrjMnuUsuariossActionPerformed(evt);
            }
        });
        meyrjMnuUsuarios.add(meyrjMnuUsuarioss);

        meyrjMnuVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        meyrjMnuVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Vendedor.png"))); // NOI18N
        meyrjMnuVendedor.setText("Vendedor");
        meyrjMnuVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meyrjMnuVendedorActionPerformed(evt);
            }
        });
        meyrjMnuUsuarios.add(meyrjMnuVendedor);

        meyrjMnuProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        meyrjMnuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos.png"))); // NOI18N
        meyrjMnuProdutos.setText("Produtos");
        meyrjMnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meyrjMnuProdutosActionPerformed(evt);
            }
        });
        meyrjMnuUsuarios.add(meyrjMnuProdutos);

        meyrjMnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        meyrjMnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        meyrjMnuSair.setText("Sair");
        meyrjMnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meyrjMnuSairActionPerformed(evt);
            }
        });
        meyrjMnuUsuarios.add(meyrjMnuSair);
        meyrjMnuUsuarios.add(jSeparator1);

        meyrjMenuBar1.add(meyrjMnuUsuarios);

        meyrjMenu2.setText("Movimento");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/venda.png"))); // NOI18N
        jMenuItem5.setText("Vendas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        meyrjMenu2.add(jMenuItem5);

        meyrjMenuBar1.add(meyrjMenu2);

        setJMenuBar(meyrjMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meyrjMnuUsuariossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meyrjMnuUsuariossActionPerformed
        // TODO add your handling code here:
        MeyrjDlgUsuarios dlg = new MeyrjDlgUsuarios(this, true); 
        dlg.setLocationRelativeTo(this); 
        dlg.setVisible(true);
    }//GEN-LAST:event_meyrjMnuUsuariossActionPerformed

    private void meyrjMnuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meyrjMnuClienteActionPerformed
        // TODO add your handling code here:
        MeyrjDlgClientes dlg = new MeyrjDlgClientes(this, true); 
        dlg.setLocationRelativeTo(this); 
        dlg.setVisible(true);
    }//GEN-LAST:event_meyrjMnuClienteActionPerformed

    private void meyrjMnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meyrjMnuProdutosActionPerformed
        // TODO add your handling code here:
        MeyrjDlgRemedios dlg = new MeyrjDlgRemedios(this, true); 
        dlg.setLocationRelativeTo(this); 
        dlg.setVisible(true);
    }//GEN-LAST:event_meyrjMnuProdutosActionPerformed

    private void meyrjMnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meyrjMnuSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_meyrjMnuSairActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        MeyrjDlgVendas dlg = new MeyrjDlgVendas(this, true); 
        dlg.setLocationRelativeTo(this); 
        dlg.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void meyrjMnuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meyrjMnuVendedorActionPerformed
        // TODO add your handling code here:
        MeyrjDlgVendedor dlg = new MeyrjDlgVendedor(this, true); 
        dlg.setLocationRelativeTo(this); 
        dlg.setVisible(true);
    }//GEN-LAST:event_meyrjMnuVendedorActionPerformed

    private void meyrjMnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meyrjMnuUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meyrjMnuUsuariosActionPerformed

    private void meyrjMnuClienteComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_meyrjMnuClienteComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_meyrjMnuClienteComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeyrJFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeyrJFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeyrJFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeyrJFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MeyrJFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JMenu meyrjMenu2;
    private javax.swing.JMenuBar meyrjMenuBar1;
    private javax.swing.JMenuItem meyrjMenuItem1;
    private javax.swing.JMenuItem meyrjMnuCliente;
    private javax.swing.JMenuItem meyrjMnuProdutos;
    private javax.swing.JMenuItem meyrjMnuSair;
    private javax.swing.JMenu meyrjMnuUsuarios;
    private javax.swing.JMenuItem meyrjMnuUsuarioss;
    private javax.swing.JMenuItem meyrjMnuVendedor;
    // End of variables declaration//GEN-END:variables

    private static class Título {

        public Título() {
        }
    }
}
