package view;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Mathias Eduardo
 */
public class MeyrjDlgLogin extends javax.swing.JDialog {

    /**
     * Creates new form MeyrjDlgLogin
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        meyrjLblUsuario = new javax.swing.JLabel();
        meyrjTxtUsuario = new javax.swing.JTextField();
        meyrjLblSenha = new javax.swing.JLabel();
        meyrLblLogin = new javax.swing.JLabel();
        meyrjBtnConfirmar = new javax.swing.JButton();
        meyrjPwdSenha = new javax.swing.JPasswordField();
        meyrjBtnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        meyrjLblUsuario.setText("Usuario:");

        meyrjTxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meyrjTxtUsuarioActionPerformed(evt);
            }
        });

        meyrjLblSenha.setText("Senha:");

        meyrLblLogin.setText("Tela de Login:");

        meyrjBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/verifique-o-simbolo-isolado_23-2150500363.jpg"))); // NOI18N
        meyrjBtnConfirmar.setText("Confirmar");
        meyrjBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meyrjBtnConfirmarActionPerformed(evt);
            }
        });

        meyrjBtnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        meyrjBtnSair.setText("Sair");
        meyrjBtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meyrjBtnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addComponent(meyrLblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(meyrjLblSenha)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(meyrjLblUsuario)
                                .addGap(14, 14, 14)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(meyrjPwdSenha)
                            .addComponent(meyrjTxtUsuario)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(meyrjBtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(meyrjBtnSair)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(meyrLblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meyrjLblUsuario)
                    .addComponent(meyrjTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meyrjLblSenha)
                    .addComponent(meyrjPwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(meyrjBtnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(meyrjBtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meyrjBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meyrjBtnConfirmarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_meyrjBtnConfirmarActionPerformed

    private void meyrjTxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meyrjTxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meyrjTxtUsuarioActionPerformed

    private void meyrjBtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meyrjBtnSairActionPerformed

    }//GEN-LAST:event_meyrjBtnSairActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel meyrLblLogin;
    private javax.swing.JButton meyrjBtnConfirmar;
    private javax.swing.JButton meyrjBtnSair;
    private javax.swing.JLabel meyrjLblSenha;
    private javax.swing.JLabel meyrjLblUsuario;
    private javax.swing.JPasswordField meyrjPwdSenha;
    private javax.swing.JTextField meyrjTxtUsuario;
    // End of variables declaration//GEN-END:variables
}
