package bean;
// Generated 06/10/2025 21:06:09 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MeyrUsuarios generated by hbm2java
 */
@Entity
@Table(name="meyr_usuarios"
    ,catalog="db_mathias_ramires"
)
public class MeyrUsuarios  implements java.io.Serializable {


     private int meyrIdUsuarios;
     private String meyrNome;
     private String meyrApelido;
     private String meyrCpf;
     private Date meyrDataNascimento;
     private String meyrSenha;
     private int meyrNivel;
     private String meyrAtivo;

    public MeyrUsuarios() {
    }

    public MeyrUsuarios(String meyrNome, String meyrApelido, String meyrCpf, Date meyrDataNascimento, String meyrSenha, int meyrNivel, String meyrAtivo) {
       this.meyrNome = meyrNome;
       this.meyrApelido = meyrApelido;
       this.meyrCpf = meyrCpf;
       this.meyrDataNascimento = meyrDataNascimento;
       this.meyrSenha = meyrSenha;
       this.meyrNivel = meyrNivel;
       this.meyrAtivo = meyrAtivo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="meyr_idUsuarios", unique=true, nullable=false)
    public int getMeyrIdUsuarios() {
        return this.meyrIdUsuarios;
    }
    
    public void setMeyrIdUsuarios(int meyrIdUsuarios) {
        this.meyrIdUsuarios = meyrIdUsuarios;
    }

    
    @Column(name="meyr_nome", length=50)
    public String getMeyrNome() {
        return this.meyrNome;
    }
    
    public void setMeyrNome(String meyrNome) {
        this.meyrNome = meyrNome;
    }

    
    @Column(name="meyr_apelido", length=25)
    public String getMeyrApelido() {
        return this.meyrApelido;
    }
    
    public void setMeyrApelido(String meyrApelido) {
        this.meyrApelido = meyrApelido;
    }

    
    @Column(name="meyr_cpf", length=14)
    public String getMeyrCpf() {
        return this.meyrCpf;
    }
    
    public void setMeyrCpf(String meyrCpf) {
        this.meyrCpf = meyrCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="meyr_dataNascimento", length=10)
    public Date getMeyrDataNascimento() {
        return this.meyrDataNascimento;
    }
    
    public void setMeyrDataNascimento(Date meyrDataNascimento) {
        this.meyrDataNascimento = meyrDataNascimento;
    }

    
    @Column(name="meyr_senha", length=20)
    public String getMeyrSenha() {
        return this.meyrSenha;
    }
    
    public void setMeyrSenha(String meyrSenha) {
        this.meyrSenha = meyrSenha;
    }

    
    @Column(name="meyr_nivel")
    public int getMeyrNivel() {
        return this.meyrNivel;
    }
    
    public void setMeyrNivel(int meyrNivel) {
        this.meyrNivel = meyrNivel;
    }

    
    @Column(name="meyr_ativo", length=1)
    public String getMeyrAtivo() {
        return this.meyrAtivo;
    }
    
    public void setMeyrAtivo(String meyrAtivo) {
        this.meyrAtivo = meyrAtivo;
    }

}


