package bean;
// Generated 06/10/2025 21:06:09 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MeyrRemedios generated by hbm2java
 */
@Entity
@Table(name="meyr_remedios"
    ,catalog="db_mathias_ramires"
)
public class MeyrRemedios  implements java.io.Serializable {


     private int meyrIdRemedio;
     private String meyrNome;
     private String meyrLaboratorio;
     private String meyrDosagem;
     private double meyrPrecoVenda;
     private double meyrPrecoCusto;
     private Date meyrDataValidade;
     private String meyrControlado;


    public MeyrRemedios() {
    }

    public MeyrRemedios(String meyrNome, String meyrLaboratorio, String meyrDosagem, double meyrPrecoVenda, double meyrPrecoCusto, Date meyrDataValidade, String meyrControlado) {
       this.meyrNome = meyrNome;
       this.meyrLaboratorio = meyrLaboratorio;
       this.meyrDosagem = meyrDosagem;
       this.meyrPrecoVenda = meyrPrecoVenda;
       this.meyrPrecoCusto = meyrPrecoCusto;
       this.meyrDataValidade = meyrDataValidade;
       this.meyrControlado = meyrControlado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="meyr_idRemedio", unique=true, nullable=false)
    public int getMeyrIdRemedio() {
        return this.meyrIdRemedio;
    }
    
    public void setMeyrIdRemedio(int meyrIdRemedio) {
        this.meyrIdRemedio = meyrIdRemedio;
    }

    
    @Column(name="meyr_nome", length=70)
    public String getMeyrNome() {
        return this.meyrNome;
    }
    
    public void setMeyrNome(String meyrNome) {
        this.meyrNome = meyrNome;
    }

    
    @Column(name="meyr_laboratorio", length=50)
    public String getMeyrLaboratorio() {
        return this.meyrLaboratorio;
    }
    
    public void setMeyrLaboratorio(String meyrLaboratorio) {
        this.meyrLaboratorio = meyrLaboratorio;
    }

    
    @Column(name="meyr_dosagem", length=30)
    public String getMeyrDosagem() {
        return this.meyrDosagem;
    }
    
    public void setMeyrDosagem(String meyrDosagem) {
        this.meyrDosagem = meyrDosagem;
    }

    
    @Column(name="meyr_precoVenda", precision=10)
    public double getMeyrPrecoVenda() {
        return this.meyrPrecoVenda;
    }
    
    public void setMeyrPrecoVenda(double meyrPrecoVenda) {
        this.meyrPrecoVenda = meyrPrecoVenda;
    }

    
    @Column(name="meyr_precoCusto", precision=10)
    public double getMeyrPrecoCusto() {
        return this.meyrPrecoCusto;
    }
    
    public void setMeyrPrecoCusto(double meyrPrecoCusto) {
        this.meyrPrecoCusto = meyrPrecoCusto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="meyr_dataValidade", length=10)
    public Date getMeyrDataValidade() {
        return this.meyrDataValidade;
    }
    
    public void setMeyrDataValidade(Date meyrDataValidade) {
        this.meyrDataValidade = meyrDataValidade;
    }

    
    @Column(name="meyr_controlado", length=1)
    public String getMeyrControlado() {
        return this.meyrControlado;
    }
    
    public void setMeyrControlado(String meyrControlado) {
        this.meyrControlado = meyrControlado;
    }
@Override
        public String toString(){
        return this.meyrNome;
    }
    
     @Override
        public boolean equals(Object object){
        if (object instanceof MeyrRemedios){
            MeyrRemedios meyrRemedios = (MeyrRemedios)object;
            if (this.getMeyrIdRemedio()== meyrRemedios.getMeyrIdRemedio()){
                return true;
            }
        }
         return false;
    }
}

