package bean;
// Generated 06/10/2025 21:06:09 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MeyrVendasRemedios generated by hbm2java
 */
@Entity
@Table(name="meyr_vendas_remedios"
    ,catalog="db_mathias_ramires"
)
public class MeyrVendasRemedios  implements java.io.Serializable {


     private int meyrIdVendasRemedio;
     private MeyrRemedios meyrRemedios;
     private MeyrVendas  meyrVendas;
     private int meyrQuantidade;
     private double meyrPrecoUnitario;
     private double meyrDesconto;

    public MeyrVendasRemedios() {
    }

    public MeyrVendasRemedios(MeyrRemedios meyrRemedios, MeyrVendas meyrVendas, int meyrQuantidade, double meyrPrecoUnitario, double meyrDesconto) {
       this.meyrRemedios = meyrRemedios;
       this.meyrVendas = meyrVendas;
       this.meyrQuantidade = meyrQuantidade;
       this.meyrPrecoUnitario = meyrPrecoUnitario;
       this.meyrDesconto = meyrDesconto;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="meyr_idVendasRemedio", unique=true, nullable=false)
    public int getMeyrIdVendasRemedio() {
        return this.meyrIdVendasRemedio;
    }
    
    public void setMeyrIdVendasRemedio(int meyrIdVendasRemedio) {
        this.meyrIdVendasRemedio = meyrIdVendasRemedio;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="meyr_idRemedio")
    public MeyrRemedios getMeyrRemedios() {
        return this.meyrRemedios;
    }
    
    public void setMeyrRemedios(MeyrRemedios meyrRemedios) {
        this.meyrRemedios = meyrRemedios;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="meyr_idVenda")
    public MeyrVendas getMeyrVendas() {
        return this.meyrVendas;
    }
    
    public void setMeyrVendas(MeyrVendas meyrVendas) {
        this.meyrVendas = meyrVendas;
    }

    
    @Column(name="meyr_quantidade")
    public int getMeyrQuantidade() {
        return this.meyrQuantidade;
    }
    
    public void setMeyrQuantidade(int meyrQuantidade) {
        this.meyrQuantidade = meyrQuantidade;
    }

    
    @Column(name="meyr_precoUnitario", precision=10)
    public double getMeyrPrecoUnitario() {
        return this.meyrPrecoUnitario;
    }
    
    public void setMeyrPrecoUnitario(double meyrPrecoUnitario) {
        this.meyrPrecoUnitario = meyrPrecoUnitario;
    }

    
    @Column(name="meyr_desconto", precision=5)
    public double getMeyrDesconto() {
        return this.meyrDesconto;
    }
    
    public void setMeyrDesconto(double meyrDesconto) {
        this.meyrDesconto = meyrDesconto;
    }
}


