package bean;
// Generated 06/10/2025 21:06:09 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MeyrVendedor generated by hbm2java
 */
@Entity
@Table(name="meyr_vendedor"
    ,catalog="db_mathias_ramires"
)
public class MeyrVendedor  implements java.io.Serializable {


     private int meyrIdVendedor;
     private String meyrNome;
     private String meyrCpf;
     private String meyrTelefone;
     private String meyrEmail;
     private Date meyrDataAdmissao;
     private int meyrAtivo;

    public MeyrVendedor() {
    }

    public MeyrVendedor(String meyrNome, String meyrCpf, String meyrTelefone, String meyrEmail, Date meyrDataAdmissao, Integer meyrAtivo) {
       this.meyrNome = meyrNome;
       this.meyrCpf = meyrCpf;
       this.meyrTelefone = meyrTelefone;
       this.meyrEmail = meyrEmail;
       this.meyrDataAdmissao = meyrDataAdmissao;
       this.meyrAtivo = meyrAtivo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="meyr_idVendedor", unique=true, nullable=false)
    public int getMeyrIdVendedor() {
        return this.meyrIdVendedor;
    }
    
    public void setMeyrIdVendedor(int meyrIdVendedor) {
        this.meyrIdVendedor = meyrIdVendedor;
    }

    
    @Column(name="meyr_nome", length=50)
    public String getMeyrNome() {
        return this.meyrNome;
    }
    
    public void setMeyrNome(String meyrNome) {
        this.meyrNome = meyrNome;
    }

    
    @Column(name="meyr_cpf", length=14)
    public String getMeyrCpf() {
        return this.meyrCpf;
    }
    
    public void setMeyrCpf(String meyrCpf) {
        this.meyrCpf = meyrCpf;
    }

    
    @Column(name="meyr_telefone", length=20)
    public String getMeyrTelefone() {
        return this.meyrTelefone;
    }
    
    public void setMeyrTelefone(String meyrTelefone) {
        this.meyrTelefone = meyrTelefone;
    }

    
    @Column(name="meyr_email", length=80)
    public String getMeyrEmail() {
        return this.meyrEmail;
    }
    
    public void setMeyrEmail(String meyrEmail) {
        this.meyrEmail = meyrEmail;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="meyr_data_admissao", length=10)
    public Date getMeyrDataAdmissao() {
        return this.meyrDataAdmissao;
    }
    
    public void setMeyrDataAdmissao(Date meyrDataAdmissao) {
        this.meyrDataAdmissao = meyrDataAdmissao;
    }

    
    @Column(name="meyr_ativo")
    public int getMeyrAtivo() {
        return this.meyrAtivo;
    }
    
    public void setMeyrAtivo(Integer meyrAtivo) {
        this.meyrAtivo = meyrAtivo;
    }
}


