package bean;
// Generated 06/10/2025 21:06:09 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MeyrClientes generated by hbm2java
 */
@Entity
@Table(name="meyr_clientes"
    ,catalog="db_mathias_ramires"
)
public class MeyrClientes  implements java.io.Serializable {


     private int meyrIdCliente;
     private String meyrNome;
     private String meyrCpf;
     private String meyrRg;
     private Date meyrDataNascimento;
     private String meyrEndereco;
     private String meyrCep;
     private String meyrBairro;
     private String meyrCidade;
     private String meyrEstado;
     private String meyrTelefone;
     private String meyrCelular;
     private String meyrEmail;
     private Date meyrDataCadastro;
     private String meyrAtivo;


    public MeyrClientes() {
    }

    public MeyrClientes(String meyrNome, String meyrCpf, String meyrRg, Date meyrDataNascimento, String meyrEndereco, String meyrCep, String meyrBairro, String meyrCidade, String meyrEstado, String meyrTelefone, String meyrCelular, String meyrEmail, Date meyrDataCadastro, String meyrAtivo) {
       this.meyrNome = meyrNome;
       this.meyrCpf = meyrCpf;
       this.meyrRg = meyrRg;
       this.meyrDataNascimento = meyrDataNascimento;
       this.meyrEndereco = meyrEndereco;
       this.meyrCep = meyrCep;
       this.meyrBairro = meyrBairro;
       this.meyrCidade = meyrCidade;
       this.meyrEstado = meyrEstado;
       this.meyrTelefone = meyrTelefone;
       this.meyrCelular = meyrCelular;
       this.meyrEmail = meyrEmail;
       this.meyrDataCadastro = meyrDataCadastro;
       this.meyrAtivo = meyrAtivo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="meyr_idCliente", unique=true, nullable=false)
    public int getMeyrIdCliente() {
        return this.meyrIdCliente;
    }
    
    public void setMeyrIdCliente(int meyrIdCliente) {
        this.meyrIdCliente = meyrIdCliente;
    }

    
    @Column(name="meyr_nome", length=70)
    public String getMeyrNome() {
        return this.meyrNome;
    }
    
    public void setMeyrNome(String meyrNome) {
        this.meyrNome = meyrNome;
    }

    
    @Column(name="meyr_cpf", length=14)
    public String getMeyrCpf() {
        return this.meyrCpf;
    }
    
    public void setMeyrCpf(String meyrCpf) {
        this.meyrCpf = meyrCpf;
    }

    
    @Column(name="meyr_rg", length=10)
    public String getMeyrRg() {
        return this.meyrRg;
    }
    
    public void setMeyrRg(String meyrRg) {
        this.meyrRg = meyrRg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="meyr_dataNascimento", length=10)
    public Date getMeyrDataNascimento() {
        return this.meyrDataNascimento;
    }
    
    public void setMeyrDataNascimento(Date meyrDataNascimento) {
        this.meyrDataNascimento = meyrDataNascimento;
    }

    
    @Column(name="meyr_endereco", length=70)
    public String getMeyrEndereco() {
        return this.meyrEndereco;
    }
    
    public void setMeyrEndereco(String meyrEndereco) {
        this.meyrEndereco = meyrEndereco;
    }

    
    @Column(name="meyr_cep", length=9)
    public String getMeyrCep() {
        return this.meyrCep;
    }
    
    public void setMeyrCep(String meyrCep) {
        this.meyrCep = meyrCep;
    }

    
    @Column(name="meyr_bairro", length=50)
    public String getMeyrBairro() {
        return this.meyrBairro;
    }
    
    public void setMeyrBairro(String meyrBairro) {
        this.meyrBairro = meyrBairro;
    }

    
    @Column(name="meyr_cidade", length=50)
    public String getMeyrCidade() {
        return this.meyrCidade;
    }
    
    public void setMeyrCidade(String meyrCidade) {
        this.meyrCidade = meyrCidade;
    }

    
    @Column(name="meyr_estado", length=2)
    public String getMeyrEstado() {
        return this.meyrEstado;
    }
    
    public void setMeyrEstado(String meyrEstado) {
        this.meyrEstado = meyrEstado;
    }

    
    @Column(name="meyr_telefone", length=14)
    public String getMeyrTelefone() {
        return this.meyrTelefone;
    }
    
    public void setMeyrTelefone(String meyrTelefone) {
        this.meyrTelefone = meyrTelefone;
    }

    
    @Column(name="meyr_celular", length=14)
    public String getMeyrCelular() {
        return this.meyrCelular;
    }
    
    public void setMeyrCelular(String meyrCelular) {
        this.meyrCelular = meyrCelular;
    }

    
    @Column(name="meyr_email", length=80)
    public String getMeyrEmail() {
        return this.meyrEmail;
    }
    
    public void setMeyrEmail(String meyrEmail) {
        this.meyrEmail = meyrEmail;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="meyr_dataCadastro", length=10)
    public Date getMeyrDataCadastro() {
        return this.meyrDataCadastro;
    }
    
    public void setMeyrDataCadastro(Date meyrDataCadastro) {
        this.meyrDataCadastro = meyrDataCadastro;
    }

    
    @Column(name="meyr_ativo", length=1)
    public String getMeyrAtivo() {
        return this.meyrAtivo;
    }
    
    public void setMeyrAtivo(String meyrAtivo) {
        this.meyrAtivo = meyrAtivo;
    }
@Override
    public String toString(){
        return this.meyrNome;
    }
    
     @Override
    public boolean equals(Object object){
        if (object instanceof MeyrClientes){
            MeyrClientes meyrClientes = (MeyrClientes)object;
            if (this.getMeyrIdCliente() == meyrClientes.getMeyrIdCliente()){
                return true;
            }
        }
         return false;
    }
}

