 package bean;
// Generated 06/10/2025 21:06:09 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MeyrVendas generated by hbm2java
 */
@Entity
@Table(name="meyr_vendas"
    ,catalog="db_mathias_ramires"
)
public class MeyrVendas  implements java.io.Serializable {


     private int meyrIdVenda;
     private MeyrClientes meyrClientes;
     private MeyrVendedor meyrVendedor;
     private Date meyrDataVenda;
     private double meyrTotalVenda;
     private String meyrFormaPagamento;
     private String meyrStatus;
     private String meyrObservacoes;


    public MeyrVendas() {
    }

    public MeyrVendas(MeyrClientes meyrClientes, MeyrVendedor meyrVendedor, Date meyrDataVenda, double meyrTotalVenda, String meyrFormaPagamento, String meyrStatus, String meyrObservacoes) {
       this.meyrClientes = meyrClientes;
       this.meyrVendedor = meyrVendedor;
       this.meyrDataVenda = meyrDataVenda;
       this.meyrTotalVenda = meyrTotalVenda;
       this.meyrFormaPagamento = meyrFormaPagamento;
       this.meyrStatus = meyrStatus;
       this.meyrObservacoes = meyrObservacoes;

    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="meyr_idVenda", unique=true, nullable=false)
    public int getMeyrIdVenda() {
        return this.meyrIdVenda;
    }
    
    public void setMeyrIdVenda(int meyrIdVenda) {
        this.meyrIdVenda = meyrIdVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="meyr_idCliente")
    public MeyrClientes getMeyrClientes() {
        return this.meyrClientes;
    }
    
    public void setMeyrClientes(MeyrClientes meyrClientes) {
        this.meyrClientes = meyrClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="meyr_idVendedor")
    public MeyrVendedor getMeyrVendedor() {
        return this.meyrVendedor;
    }
    
    public void setMeyrVendedor(MeyrVendedor meyrVendedor) {
        this.meyrVendedor = meyrVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="meyr_dataVenda", length=10)
    public Date getMeyrDataVenda() {
        return this.meyrDataVenda;
    }
    
    public void setMeyrDataVenda(Date meyrDataVenda) {
        this.meyrDataVenda = meyrDataVenda;
    }

    
    @Column(name="meyr_totalVenda", precision=10)
    public double getMeyrTotalVenda() {
        return this.meyrTotalVenda;
    }
    
    public void setMeyrTotalVenda(double meyrTotalVenda) {
        this.meyrTotalVenda = meyrTotalVenda;
    }

    
    @Column(name="meyr_formaPagamento", length=20)
    public String getMeyrFormaPagamento() {
        return this.meyrFormaPagamento;
    }
    
    public void setMeyrFormaPagamento(String meyrFormaPagamento) {
        this.meyrFormaPagamento = meyrFormaPagamento;
    }

    
    @Column(name="meyr_status", length=15)
    public String getMeyrStatus() {
        return this.meyrStatus;
    }
    
    public void setMeyrStatus(String meyrStatus) {
        this.meyrStatus = meyrStatus;
    }

    
    @Column(name="meyr_observacoes", length=80)
    public String getMeyrObservacoes() {
        return this.meyrObservacoes;
    }
    
    public void setMeyrObservacoes(String meyrObservacoes) {
        this.meyrObservacoes = meyrObservacoes;
    }
}


